name: Deploy Frontend React s3 static hosting

on:
  workflow_dispatch:  

jobs:
  build-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.19.1'

      - name: Install dependencies
        run: npm ci

      - name: Generate .env file for Vite (based on branch)
        run: |
          echo "[FRONTEND] Generating .env file for branch: ${{ github.ref_name }}"
          echo "VITE_IS_QA=prod" >> .env
          echo "VITE_API_BASE_URL=https://koco-test.click/" >> .env
          echo "VITE_REDIRECT_URL=https://koco-test.click/oauth/kakao/callback" >> .env
          echo "VITE_KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env

      - name: Build React App
        run: npm run build

      - name: Deploy to Static Hosting S3
        run: |
          # 브랜치에 따라 호스팅용 S3 버킷 결정
          if [ "${{ github.ref_name }}" = "main" ]; then
            BUCKET="eks-test-koco-front-s3"
          else
            BUCKET="dev-koco-front-s3"
          fi
          echo "[FRONTEND] Syncing ./dist → s3://$BUCKET"
          aws s3 sync ./dist s3://$BUCKET --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          
      - name: Invalidate CloudFront cache
        run: |
          DOMAIN="koco-test.click"

          DIST_ID=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?Aliases.Items[?contains(@, '$DOMAIN')]].Id" \
            --output text)

          echo "[FRONTEND] Invalidating CloudFront ($DOMAIN) cache → $DIST_ID"
          aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
